version: '3.8'
services:
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - api-network
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGO_HOST=mongodb
    depends_on:
      - mongodb
    networks:
      - api-network
networks:
  api-network:
    driver: bridge
